export const settings = {
    mobileMenuLinkSelector: '.mobile-menu a',
    menuToggleId: 'menu-toggle',
    submenuCheckboxSelector: '.submenu-checkbox',
    heroSlideSelector: '.hero__slide',
    heroPreviousSelector: '.hero__nav--previous',
    heroNextSelector: '.hero__nav--next',
    isActiveClass: 'is-active',
    tickerTrackSelector: '.ticker__track',
    tickerPreviousSelector: '.ticker__nav--previous',
    tickerNextSelector: '.ticker__nav--next',
    tickerItemSelector: '.ticker__item',
    tickerInnerSelector: '.ticker__inner',
    productsTrackSelector: '.products__track',
    productsPreviousSelector: '.products__nav--previous',
    productsNextSelector: '.products__nav--next',
    productCardSelector: '.product__card',
    filterInputSelector: 'input[name="filter"]',
    footerTickerTrackSelector: '.footer-ticker__track',
    emailButtonSelector: '.contact__email',
    copiedClass: 'copied',
    emailButtonText: 'Copié !',
}